@baseUrl = https://localhost:5001

# get blockchain
GET {{baseUrl}}/chain

###

# mine a block
GET {{baseUrl}}/mine

###

# create a new transaction
POST {{baseUrl}}/transactions/new
Content-Type: application/json

{
    "sender": "me",
    "recipient": "you",
    "amount": 42
}

###

# invalid call for a new transaction
POST {{baseUrl}}/transactions/new
Content-Type: application/json

{}